//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProductWebService.ProductWebServiceConsumer
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunSonuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UrunSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UrunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        private System.Nullable<decimal> FiyatField;
        
        private System.Nullable<short> StokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UrunID {
            get {
                return this.UrunIDField;
            }
            set {
                if ((this.UrunIDField.Equals(value) != true)) {
                    this.UrunIDField = value;
                    this.RaisePropertyChanged("UrunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((this.FiyatField.Equals(value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<short> Stok {
            get {
                return this.StokField;
            }
            set {
                if ((this.StokField.Equals(value) != true)) {
                    this.StokField = value;
                    this.RaisePropertyChanged("Stok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductWebServiceConsumer.ProductWebServiceSoap")]
    public interface ProductWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name UrunleriGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunleriGetir", ReplyAction="*")]
        ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponse UrunleriGetir(ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunleriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponse> UrunleriGetirAsync(ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunleriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunleriGetir", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequestBody Body;
        
        public UrunleriGetirRequest() {
        }
        
        public UrunleriGetirRequest(ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UrunleriGetirRequestBody {
        
        public UrunleriGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunleriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunleriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponseBody Body;
        
        public UrunleriGetirResponse() {
        }
        
        public UrunleriGetirResponse(ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrunleriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientProductWebService.ProductWebServiceConsumer.UrunSonuc[] UrunleriGetirResult;
        
        public UrunleriGetirResponseBody() {
        }
        
        public UrunleriGetirResponseBody(ClientProductWebService.ProductWebServiceConsumer.UrunSonuc[] UrunleriGetirResult) {
            this.UrunleriGetirResult = UrunleriGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWebServiceSoapChannel : ClientProductWebService.ProductWebServiceConsumer.ProductWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWebServiceSoapClient : System.ServiceModel.ClientBase<ClientProductWebService.ProductWebServiceConsumer.ProductWebServiceSoap>, ClientProductWebService.ProductWebServiceConsumer.ProductWebServiceSoap {
        
        public ProductWebServiceSoapClient() {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponse ClientProductWebService.ProductWebServiceConsumer.ProductWebServiceSoap.UrunleriGetir(ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest request) {
            return base.Channel.UrunleriGetir(request);
        }
        
        public ClientProductWebService.ProductWebServiceConsumer.UrunSonuc[] UrunleriGetir() {
            ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest inValue = new ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest();
            inValue.Body = new ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequestBody();
            ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponse retVal = ((ClientProductWebService.ProductWebServiceConsumer.ProductWebServiceSoap)(this)).UrunleriGetir(inValue);
            return retVal.Body.UrunleriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponse> ClientProductWebService.ProductWebServiceConsumer.ProductWebServiceSoap.UrunleriGetirAsync(ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest request) {
            return base.Channel.UrunleriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirResponse> UrunleriGetirAsync() {
            ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest inValue = new ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequest();
            inValue.Body = new ClientProductWebService.ProductWebServiceConsumer.UrunleriGetirRequestBody();
            return ((ClientProductWebService.ProductWebServiceConsumer.ProductWebServiceSoap)(this)).UrunleriGetirAsync(inValue);
        }
    }
}
